var STRINGS = {
    en: {
        pageTitle: "Status | Gym High Bar",
        heading: "Gym High Bar Status",
        loading: "Loading…",
        operational: "Operational",
        down: "Down",
        unknown: "Unknown",
        barUp: "{date} — {percent}% up",
        barNoData: "{date} — no data",
        uptime: "{percent}% uptime",
        noData: "no data yet",
        staleHeadline: "Status is out of date",
        staleSub: "The monitor has not reported recently, so this page cannot say whether services are healthy. Last report: {when}.",
        okHeadline: "All systems operational",
        lastChecked: "Last checked {when}.",
        oneDown: "{name} is down",
        manyDown: "{count} services are down",
        unavailableHeadline: "Status is unavailable",
        unavailableSub: "The status feed could not be reached. This says nothing about the services themselves.",
        justNow: "just now",
        unknownTime: "unknown",
        footer: "Checked every 30 minutes from outside our network."
    },
    ru: {
        pageTitle: "Статус | Gym High Bar",
        heading: "Статус Gym High Bar",
        loading: "Загрузка…",
        operational: "Работает",
        down: "Не работает",
        unknown: "Неизвестно",
        barUp: "{date} — доступно {percent}%",
        barNoData: "{date} — нет данных",
        uptime: "доступность {percent}%",
        noData: "пока нет данных",
        staleHeadline: "Статус устарел",
        staleSub: "Мониторинг давно не присылал данных, поэтому страница не может сказать, работают ли сервисы. Последний отчёт: {when}.",
        okHeadline: "Все системы работают",
        lastChecked: "Последняя проверка: {when}.",
        oneDown: "{name}: не работает",
        manyDown: "Не работает сервисов: {count}",
        unavailableHeadline: "Статус недоступен",
        unavailableSub: "Не удалось получить данные о статусе. Это ничего не говорит о работе самих сервисов.",
        justNow: "только что",
        unknownTime: "неизвестно",
        footer: "Проверяется каждые 30 минут извне нашей сети.",
        "service:game-services": "Игровые сервисы",
        "service:platform": "Платформа",
        "service:legacy": "Старые серверы"
    },
    ja: {
        pageTitle: "ステータス | Gym High Bar",
        heading: "Gym High Bar ステータス",
        loading: "読み込み中…",
        operational: "正常",
        down: "停止中",
        unknown: "不明",
        barUp: "{date} — 稼働率 {percent}%",
        barNoData: "{date} — データなし",
        uptime: "稼働率 {percent}%",
        noData: "データなし",
        staleHeadline: "ステータスが古くなっています",
        staleSub: "監視システムからの報告が最近ないため、サービスが正常かどうか判断できません。最後の報告：{when}。",
        okHeadline: "すべてのシステムが正常です",
        lastChecked: "最終確認：{when}。",
        oneDown: "{name}が停止中です",
        manyDown: "{count}個のサービスが停止中です",
        unavailableHeadline: "ステータスを取得できません",
        unavailableSub: "ステータス情報に接続できませんでした。サービス自体の状態とは関係ありません。",
        justNow: "たった今",
        unknownTime: "不明",
        footer: "30分ごとに外部ネットワークから確認しています。",
        "service:game-services": "ゲームサービス",
        "service:platform": "プラットフォーム",
        "service:legacy": "旧サーバー"
    }
};
