var STRINGS = {
    en: {
        pageTitle: "Next Update | Gym High Bar",
        title: "Next Update",
        lead: "A big update is on the way.",
        target: "Aiming for October 2026",
        targetNote: "Not a promise. The date could move a little.",
        progress: "How the update is going",
        stepMaking: "Making the update",
        stepOnline: "Online features",
        stepServers: "New servers",
        stepTrailer: "Trailer and pictures",
        stepReview: "Apple & Google check it",
        stepOut: "Out!",
        done: "Done",
        now: "Working on it",
        next: "Soon",
        updated: "Last updated: {date}",
        safeTitle: "Your progress comes with you",
        safeText: "Your account and everything you unlocked carry over to the update.",
        note1: "I'm building this update on my own, and it's almost ready.",
        note2: "I'll share the release day as soon as I know it.",
        note3: "Follow me with the button below so you don't miss any news!",
        note4: "Thank you for waiting and for supporting me! ❤️",
        more: "More news soon 👀",
        follow: "Follow for news"
    },
    ru: {
        pageTitle: "Следующее обновление | Gym High Bar",
        title: "Следующее обновление",
        lead: "Большое обновление уже в пути.",
        target: "Планирую на октябрь 2026",
        targetNote: "Это не обещание. Дата может немного сдвинуться.",
        progress: "Как идёт работа",
        stepMaking: "Создание обновления",
        stepOnline: "Онлайн-функции",
        stepServers: "Новые серверы",
        stepTrailer: "Трейлер и картинки",
        stepReview: "Проверка Apple и Google",
        stepOut: "Выход!",
        done: "Готово",
        now: "В работе",
        next: "Скоро",
        updated: "Обновлено: {date}",
        safeTitle: "Твой прогресс останется с тобой",
        safeText: "Твой аккаунт и всё открытое перейдут в обновление.",
        note1: "Я делаю это обновление сам, и оно почти готово.",
        note2: "Я сообщу дату выхода, как только буду её знать.",
        note3: "Подписывайтесь на меня по кнопке ниже, чтобы не пропустить новости!",
        note4: "Спасибо, что ждёте и поддерживаете меня! ❤️",
        more: "Скоро будет больше новостей 👀",
        follow: "Следить за новостями"
    },
    ja: {
        pageTitle: "次のアップデート | Gym High Bar",
        title: "次のアップデート",
        lead: "大きなアップデートを準備中！",
        target: "2026年10月を予定",
        targetNote: "確定ではありません。日付は少し変わるかもしれません。",
        progress: "開発の進み具合",
        stepMaking: "アップデート制作",
        stepOnline: "オンライン機能",
        stepServers: "新しいサーバー",
        stepTrailer: "トレーラーと画像",
        stepReview: "AppleとGoogleの審査",
        stepOut: "リリース！",
        done: "完了",
        now: "作業中",
        next: "もうすぐ",
        updated: "最終更新：{date}",
        safeTitle: "進行状況はそのまま引き継がれます",
        safeText: "アカウントとアンロックしたものは、すべてアップデート後も引き継がれます。",
        note1: "このアップデートは一人で作っていて、もうすぐ完成します。",
        note2: "リリース日が決まったら、すぐにお知らせします。",
        note3: "最新情報を見逃さないように、下のボタンからフォローしてね！",
        note4: "待っていてくれて、応援してくれてありがとう！❤️",
        more: "続報をお楽しみに 👀",
        follow: "最新情報をフォロー"
    }
};
